{ ... }:
let
  # See ../../apps/default.nix for what this does.
  apps = import ../../apps;
in
{
  imports = [
    # Generated by nixos-generate-config. Sole source of truth for disks,
    # filesystems and swap. Do not edit.
    ./hardware-configuration.nix

    # System: what makes the machine work at all. Not apps - this is the part
    # that is genuinely per-machine.
    ../../system/core.nix
    ../../system/desktop.nix
    ../../system/greeter.nix
    ../../system/home-manager.nix

    # Apps this machine gets. One name per line, each one a file in ../../apps.
    # Add a line to install an app here; delete one to remove it. The desktop
    # keeps its own copy of this list, so the two machines can be identical
    # without being forced to be.
    (apps [
      "btop"
      "citrix"
      "fastfetch"
      "fonts"
      "ghostty"
      "git"
      "loupe"
      "neovim"
      "noctalia"
      "obsidian"
      "tmux"
      "yazi"
      "zed"
      "zen"
      "zsh"
    ])
  ];

  networking.hostName = "thinkpad";

  # The NixOS release this machine was first installed from. Do not bump.
  system.stateVersion = "26.05";
}
